//! The OData CSDL standard end to end: repaired in place, never created
//! or moved, and legacy versions only checked.

use bc_api_spec::diagnostic::Code;

use super::*;

const CDS: &str = "srv/catalog-service.cds";
const METADATA: &str = "srv/$metadata.xml";

/// A SAP CAP service (no HTTP framework) exposing one entity set and one
/// action.
fn cap_repo() -> tempfile::TempDir {
    let root = tempfile::tempdir().unwrap();
    write(
        root.path(),
        "package.json",
        r#"{"dependencies":{"@sap/cds":"8"}}"#,
    );
    write(
        root.path(),
        CDS,
        "using my.bookshop as my from '../db/schema';\nservice CatalogService {\n  entity Books as projection on my.Books;\n  action submitOrder(book : Integer, quantity : Integer);\n}\n",
    );
    root
}

fn cap_inventory() -> serde_json::Value {
    json!([
        {"method": "entity_set", "path": "Books", "file": CDS, "line": 3,
         "snippet": "entity Books as projection on my.Books;"},
        {"method": "ACTION", "path": "submitOrder", "file": CDS, "line": 4,
         "snippet": "action submitOrder("},
    ])
}

/// A complete OData 4.0 CSDL document for it.
const CATALOG: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by cds compile, kept for the UI mock server -->
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:Reference Uri="https://oasis-tcs.github.io/odata-vocabularies/vocabularies/Org.OData.Core.V1.xml">
    <edmx:Include Namespace="Org.OData.Core.V1" Alias="Core"/>
  </edmx:Reference>
  <edmx:DataServices>
    <Schema Namespace="CatalogService" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityContainer Name="EntityContainer">
        <EntitySet Name="Books" EntityType="CatalogService.Books"/>
        <ActionImport Name="submitOrder" Action="CatalogService.submitOrder"/>
      </EntityContainer>
      <EntityType Name="Books">
        <Key><PropertyRef Name="ID"/></Key>
        <Property Name="ID" Type="Edm.Int32" Nullable="false"/>
        <Property Name="title" Type="Edm.String"/>
      </EntityType>
      <Action Name="submitOrder" IsBound="false">
        <Parameter Name="book" Type="Edm.Int32"/>
        <Parameter Name="quantity" Type="Edm.Int32"/>
      </Action>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
"#;

const KEY: &str = "\n        <Key><PropertyRef Name=\"ID\"/></Key>";

/// The same document with the entity type's key missing.
fn keyless() -> String {
    CATALOG.replace(KEY, "")
}

fn key_repair() -> serde_json::Value {
    json!([{"old": "<EntityType Name=\"Books\">",
            "new": format!("<EntityType Name=\"Books\">{KEY}")}])
}

fn cap_reply(decision: &str, edits: serde_json::Value) -> String {
    json!({"decision": decision, "edits": edits, "inventory": cap_inventory()}).to_string()
}

fn only_odata(assurance: &Assurance) -> &SpecOutcome {
    let outcome = only(assurance);
    assert_eq!(outcome.spec_format, FormatId::OData);
    outcome
}

#[tokio::test]
async fn a_missing_csdl_is_never_created_and_the_note_says_why() {
    let root = cap_repo();
    let client = Client::new(Vec::new());
    let assurance = run_step(root.path(), &config(), &client).await;
    assert_eq!(client.calls(), 0);
    assert_eq!(assurance.api_spec.state, "skipped");
    assert!(assurance.api_spec.documents.is_empty());
    let note = &assurance.api_spec.notes[0];
    assert!(
        note.starts_with("OData CSDL: No document is created for the service at .: SAP CAP"),
        "{note}"
    );
    assert!(!root.path().join(METADATA).exists());
}

#[tokio::test]
async fn a_valid_complete_csdl_is_left_unchanged() {
    let root = cap_repo();
    write(root.path(), METADATA, CATALOG);
    let client = Client::texts(&[cap_reply("no_change", json!([])), review(true)]);
    let assurance = run_step(root.path(), &config(), &client).await;
    let outcome = only_odata(&assurance);
    assert_eq!(outcome.action, SpecAction::Complete);
    assert_eq!(outcome.version, Some(SpecVersion::Odata4));
    assert_eq!(outcome.syntax, Some(Syntax::Xml));
    assert_eq!(outcome.frameworks, ["sap_cap"]);
    assert!(outcome.diagnostics_before.is_empty());
    assert!(outcome.convention.contains("never created"));
    assert_eq!(read(root.path(), METADATA), CATALOG);
}

#[tokio::test]
async fn a_broken_csdl_is_repaired_with_a_minimal_edit() {
    let root = cap_repo();
    write(root.path(), METADATA, &keyless());
    let client = Client::texts(&[cap_reply("repair", key_repair()), review(true)]);
    let assurance = run_step(root.path(), &config(), &client).await;
    let outcome = only_odata(&assurance);
    assert_eq!(outcome.action, SpecAction::Repaired);
    assert!(outcome.diagnostics_before.iter().any(|diagnostic| {
        diagnostic.code == Code::MissingKey && diagnostic.pointer == "/types/CatalogService.Books"
    }));
    assert!(outcome.diagnostics_after.is_empty());
    assert_eq!(read(root.path(), METADATA), CATALOG);
    assert!(client.prompt(0).contains("kept for the UI mock server"));
}

#[tokio::test]
async fn a_csdl_json_document_is_repaired_in_its_own_syntax() {
    let root = cap_repo();
    let path = "srv/catalog.csdl.json";
    let complete = "{\n  \"$Version\": \"4.01\",\n  \"$EntityContainer\": \"CatalogService.EntityContainer\",\n  \"CatalogService\": {\n    \"Books\": {\"$Kind\": \"EntityType\", \"$Key\": [\"ID\"], \"ID\": {\"$Type\": \"Edm.Int32\"}},\n    \"submitOrder\": [{\"$Kind\": \"Action\", \"$Parameter\": [{\"$Name\": \"book\", \"$Type\": \"Edm.Int32\"}]}],\n    \"EntityContainer\": {\"$Kind\": \"EntityContainer\",\n      \"Books\": {\"$Collection\": true, \"$Type\": \"CatalogService.Books\"},\n      \"submitOrder\": {\"$Action\": \"CatalogService.submitOrder\"}}\n  }\n}\n";
    let missing_set = complete.replace(
        ",\n      \"Books\": {\"$Collection\": true, \"$Type\": \"CatalogService.Books\"}",
        "",
    );
    write(root.path(), path, &missing_set);
    let edits = json!([{"old": "{\"$Kind\": \"EntityContainer\",\n",
                        "new": "{\"$Kind\": \"EntityContainer\",\n      \"Books\": {\"$Collection\": true, \"$Type\": \"CatalogService.Books\"},\n"}]);
    let client = Client::texts(&[cap_reply("repair", edits), review(true)]);
    let assurance = run_step(root.path(), &config(), &client).await;
    let outcome = only_odata(&assurance);
    assert_eq!(outcome.syntax, Some(Syntax::Json));
    assert_eq!(outcome.action, SpecAction::Repaired, "{outcome:?}");
    assert!(outcome.diagnostics_after.is_empty());
    let written = read(root.path(), path);
    assert!(written.contains("\"Books\": {\"$Collection\": true"));
}

#[tokio::test]
async fn a_repair_that_drops_an_entity_set_is_refused() {
    let root = cap_repo();
    write(root.path(), METADATA, &keyless());
    let dropping = json!([
        {"old": "<EntityType Name=\"Books\">", "new": format!("<EntityType Name=\"Books\">{KEY}")},
        {"old": "        <EntitySet Name=\"Books\" EntityType=\"CatalogService.Books\"/>\n", "new": ""},
    ]);
    let reply = cap_reply("repair", dropping);
    let client = Client::texts(&[reply.clone(), reply.clone(), reply]);
    let assurance = run_step(root.path(), &config(), &client).await;
    let outcome = only_odata(&assurance);
    assert_eq!(outcome.action, SpecAction::Rejected);
    assert!(outcome
        .gaps
        .last()
        .unwrap()
        .contains("removed documented entity set `CatalogService.EntityContainer.Books`"));
    assert_eq!(read(root.path(), METADATA), keyless());
}

#[tokio::test]
async fn a_remote_reference_is_unverifiable_and_never_fetched() {
    let server = wiremock::MockServer::start().await;
    let root = cap_repo();
    let referencing = CATALOG.replace(
        "  <edmx:DataServices>",
        &format!(
            "  <edmx:Reference Uri=\"{}/common.xml\"><edmx:Include Namespace=\"Common\"/></edmx:Reference>\n  <edmx:DataServices>",
            server.uri()
        ),
    );
    write(root.path(), METADATA, &referencing);
    let client = Client::texts(&[cap_reply("no_change", json!([])), review(true)]);
    let assurance = run_step(root.path(), &config(), &client).await;
    let outcome = only_odata(&assurance);
    assert_eq!(outcome.action, SpecAction::Complete);
    assert_eq!(outcome.diagnostics_before.len(), 1);
    assert_eq!(outcome.diagnostics_before[0].code, Code::ExternalRef);
    assert_eq!(server.received_requests().await.unwrap().len(), 0);
}

#[tokio::test]
async fn a_doctype_leaves_the_csdl_untouched() {
    let root = cap_repo();
    let doctype = CATALOG.replace("<!-- Generated", "<!DOCTYPE edmx>\n<!-- Generated");
    write(root.path(), METADATA, &doctype);
    let client = Client::new(Vec::new());
    let assurance = run_step(root.path(), &config(), &client).await;
    let outcome = only_odata(&assurance);
    assert_eq!(outcome.action, SpecAction::Unverifiable);
    assert!(outcome.gaps[0].contains("DOCTYPE"));
    assert_eq!(client.calls(), 0);
}

#[tokio::test]
async fn a_rejected_review_leaves_the_csdl_unchanged() {
    let root = cap_repo();
    write(root.path(), METADATA, &keyless());
    let client = Client::texts(&[cap_reply("repair", key_repair()), review(false)]);
    let assurance = run_step(root.path(), &config(), &client).await;
    assert_eq!(only_odata(&assurance).action, SpecAction::Rejected);
    assert_eq!(read(root.path(), METADATA), keyless());
}

#[tokio::test]
async fn a_credential_in_a_repair_is_never_written() {
    let root = cap_repo();
    write(root.path(), METADATA, &keyless());
    let leaky = json!([
        {"old": "<EntityType Name=\"Books\">", "new": format!("<EntityType Name=\"Books\">{KEY}")},
        {"old": "<Property Name=\"title\" Type=\"Edm.String\"/>",
         "new": "<Property Name=\"title\" Type=\"Edm.String\" DefaultValue=\"token: abcdefgh12345\"/>"},
    ]);
    let reply = cap_reply("repair", leaky);
    let client = Client::texts(&[reply.clone(), reply.clone(), reply]);
    let assurance = run_step(root.path(), &config(), &client).await;
    let outcome = only_odata(&assurance);
    assert_eq!(outcome.action, SpecAction::Rejected);
    assert!(outcome
        .gaps
        .last()
        .unwrap()
        .contains("look like credentials"));
    assert_eq!(read(root.path(), METADATA), keyless());
}

#[tokio::test]
async fn legacy_metadata_is_reported_and_never_rewritten() {
    let root = cap_repo();
    let legacy = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edmx\" xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\">\n  <edmx:DataServices m:DataServiceVersion=\"2.0\">\n    <Schema Namespace=\"CatalogService\" xmlns=\"http://schemas.microsoft.com/ado/2008/09/edm\">\n      <EntityType Name=\"Books\"><Property Name=\"ID\" Type=\"Edm.Int32\"/></EntityType>\n      <EntityContainer Name=\"Entities\"><EntitySet Name=\"Books\" EntityType=\"CatalogService.Books\"/></EntityContainer>\n    </Schema>\n  </edmx:DataServices>\n</edmx:Edmx>\n";
    write(root.path(), "webapp/localService/metadata.xml", legacy);
    let client = Client::new(Vec::new());
    let assurance = run_step(root.path(), &config(), &client).await;
    assert_eq!(client.calls(), 0);
    let outcome = only_odata(&assurance);
    assert_eq!(outcome.action, SpecAction::Reported);
    assert_eq!(outcome.version, Some(SpecVersion::Odata2));
    let codes: Vec<Code> = outcome.diagnostics_before.iter().map(|d| d.code).collect();
    assert_eq!(codes, [Code::LegacyVersion, Code::MissingKey]);
    assert!(outcome.gaps[0].contains("legacy"));
    assert_eq!(
        read(root.path(), "webapp/localService/metadata.xml"),
        legacy
    );
}

#[tokio::test]
async fn a_csdl_outside_the_service_is_never_moved() {
    let root = cap_repo();
    write(root.path(), "docs/Catalog.edmx", CATALOG);
    let client = Client::texts(&[cap_reply("no_change", json!([])), review(true)]);
    let assurance = run_step(root.path(), &config(), &client).await;
    let outcome = only_odata(&assurance);
    assert_eq!(outcome.action, SpecAction::Complete);
    assert_eq!(outcome.path, "docs/Catalog.edmx");
    assert_eq!(outcome.previous_path, None);
}
