[package]
name = "bc-report-md"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
bc-model = { path = "../bc-model" }
bc-cwe = { path = "../bc-cwe" }
bc-validation-scoring = { path = "../bc-validation-scoring" }
regex = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
