[package]
name = "bc-llm-openai"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
bc-llm-client = { path = "../bc-llm-client" }
serde_json = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
regex = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wiremock = { workspace = true }
