[package]
name = "bc-gateway-http"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
reqwest = { workspace = true }
rustls-pki-types = { workspace = true }
bc-pathjail = { path = "../bc-pathjail" }

[dev-dependencies]
tempfile = { workspace = true }
